
name: Unit tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]


    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Copy .env.test
        run: cp .envrc.template .envrc
        working-directory: ./node/express-prisma-typescript
      - name: yarn install
        run: yarn install
        working-directory: ./node/express-prisma-typescript
      - name: tests
        run: yarn test
        working-directory: ./node/express-prisma-typescript